format = """
[](color_bg0)\
$os\
$username\
[](fg:color_bg0 bg:color_bg1)\
$directory\
[](fg:color_bg1 bg:color_bg2)\
$git_branch\
$git_status\
[](fg:color_bg2 bg:color_bg3)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_bg3 bg:color_bg4)\
$docker_context\
$conda\
[](fg:color_bg4 bg:color_bg5)\
$time\
$cmd_duration\
[ ](color_bg5)\
$line_break$character"""

#palette = 'tokyo_night'

#palette = 'gruvbox_dark'

#palette = 'coffee_box'

#palette = 'sunset'

palette = 'dark_seafoam'

[palettes.tokyo_night]
color_fg0 = '#090c0c'
color_bg0 = '#a3aed2'
color_fg1 = '#e3e5e5'
color_bg1 = '#769ff0'
color_fg2 = '#769ff0'
color_bg2 = '#394260'
color_fg3 = '#779ff0'
color_bg3 = '#212736'
color_fg4 = '#779ff0'
color_bg4 = '#1d2230'
color_fg5 = '#a0a9cb'
color_bg5 = '#1d2230'
color_green = '#98971a'
color_purple = '#b16286'
color_red = '#cc241d'


[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg0 = '#d65d0e'
color_fg1 = '#fbf1c7'
color_bg1 = '#d79921'
color_fg2 = '#fbf1c7'
color_bg2 = '#689d6a'
color_fg3 = '#fbf1c7'
color_bg3 = '#458588'
color_fg4 = '#83a598'
color_bg4 = '#665c54'
color_fg5 = '#fbf1c7'
color_bg5 = '#3c3836'
color_green = '#98971a'
color_purple = '#b16286'
color_red = '#cc241d'

[palettes.coffee_box]
color_fg0 = '#E6E0D0'
color_bg0 = '#CEC3B1'
color_fg1 = '#CEC3B1'
color_bg1 = '#B6A691'
color_fg2 = '#B6A691'
color_bg2 = '#9F8872'
color_fg3 = '#9F8872'
color_bg3 = '#876B52'
color_fg4 = '#876B52'
color_bg4 = '#6F4E33'
color_fg5 = '#704214'
color_bg5 = '#704214'
color_green = '#98971a'
color_purple = '#b16286'
color_red = '#cc241d'

[palettes.sunset]
color_fg0 = '#380202'
color_bg0 = '#FFC95F'
color_fg1 = '#380202'
color_bg1 = '#FF8120'
color_fg2 = '#FFC95F'
color_bg2 = '#F55203'
color_fg3 = '#FF8120'
color_bg3 = '#9A2400'
color_fg4 = '#7E2D00'
color_bg4 = '#7E2D00'
color_fg5 = '#F55203'
color_bg5 = '#380202'
color_green = '#98971a'
color_purple = '#b16286'
color_red = '#cc241d'

[palettes.dark_seafoam]
color_fg0 = '#000000'
color_bg0 = '#199162'
color_fg1 = '#03120C'
color_bg1 = '#136D49'
color_fg2 = '#1CA36E'
color_bg2 = '#0C4831'
color_fg3 = '#1CA36E'
color_bg3 = '#093625'
color_fg4 = '#1CA36E'
color_bg4 = '#062418'
color_fg5 = '#1CA36E'
color_bg5 = '#03120C'
color_green = '#98971A'
color_purple = '#B16286'
color_red = '#CC241D'

[os]
disabled = false
style = "bg:color_bg0 fg:color_fg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:color_bg0 fg:color_fg0"
style_root = "bg:color_bg0 fg:color_fg0"
format = '[ $user ]($style)'

[directory]
style = "fg:color_fg1 bg:color_bg1"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_bg2"
format = '[[ $symbol $branch ](fg:color_fg2 bg:color_bg2)]($style)'

[git_status]
style = "bg:color_bg2"
format = '[[($all_status$ahead_behind )](fg:color_fg2 bg:color_bg2)]($style)'

[nodejs]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $version) ](fg:color_fg3 bg:color_bg3)]($style)'

[c]
symbol = " "
style = "bg:color_bg3"
format = '[[ $symbol( $version) ](fg:color_fg3 bg:color_bg3)]($style)'

[rust]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $version) ](fg:color_fg3 bg:color_bg3)]($style)'

[golang]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $version) ](fg:color_fg3 bg:color_bg3)]($style)'

[php]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $version) ](fg:color_fg3 bg:color_bg3)]($style)'

[java]
symbol = " "
style = "bg:color_bg3"
format = '[[ $symbol( $version) ](fg:color_fg3 bg:color_bg3)]($style)'

[kotlin]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $version) ](fg:color_fg3 bg:color_bg3)]($style)'

[haskell]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $version) ](fg:color_fg3 bg:color_bg3)]($style)'

[python]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $version) ](fg:color_fg3 bg:color_bg3)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg4"
format = '[[ $symbol( $context) ](fg:color_fg4 bg:color_bg4)]($style)'

[conda]
style = "bg:color_bg4"
format = '[[ $symbol( $environment) ](fg:color_fg4 bg:color_bg4)]($style)'

[time]
disabled = true
time_format = "%R"
style = "bg:color_bg5"
format = '[[  $time ](fg:color_fg5 bg:color_bg5)]($style)'

[cmd_duration]
style = "bg:color_bg5"
format = '[[  $duration ](fg:color_fg5 bg:color_bg5)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_bg1)'

[custom.ranger]
disabled = false
style = "fg:color_fg1 bg:color_bg1"
symbol = "󰓾"
command = 'echo $RANGER_LEVEL'
format = '[[ $symbol( $output)]($style)]($style)'
when = ''' test "$RANGER_LEVEL"'''
